### PR TITLE
Docker-compose build

### PR DESCRIPTION
**Pull request by dimitriin**

### CODE REVIEW

**Comment by RichardKnop** [comment]
Any description? What is the purpose of this PR?

**Comment by dimitriin** [comment]
@RichardKnop, It's good to run go-oauth-server in Docker container, but it's better to run also etcd and postgres in containers. So I prepared docker-compose configuration to start auth-server, postgers and etcd in separate linked containers. Also during up process all configuration and fixtures will be loaded. So in development or demo purposes to start app you only need to run:
 ```
docker-compose up
```

**Comment by RichardKnop** [comment]
@dimitriin OK. I need to think about this. Right now the `Dockerfile` can be used for deployment in AWS, let's say you are using RDS for database and etc hosted on another EC2 instance. This change would probably not make deployment like that easy.

I'm afraid this change in `docker-entrypoint` might make deployment like this more difficult. Perhaps have a separate Dockerfile and entrypoint for docker compose?

**Comment by dimitriin** [comment]
@RichardKnop , I have moved docker-compose configuration to separate files (docker-entrypoint.sh and Dockerfile).

**Comment by RichardKnop** [comment]
Great! :+1: 

Thank you for the good work.

**Comment by krak3n** [comment]
When I try and run this with `docker-compose up` it errors with:

```
oauth2-server_1 | 2016/03/23 14:56:14 ETCD Endpoint: http://etcd:2379
oauth2-server_1 | 2016/03/23 14:56:15 client: etcd cluster is unavailable or misconfigured
```

```
Docker version 1.10.2, build c3959b1
```

**Comment by dimitriin** [comment]
@krak3n,
I suppose, `oauth2-server` starts before `etcd` started. To avoid this problem in `docker-entrypoint.sh` increase sleep value or try to up services one by one:
* `docker-compose up etcd`
* `docker-compose up pg`
* `docker-compose up oauth2-server`

**Pull request merged**
