### PR TITLE
Update to etcd v3

### PR DESCRIPTION
**Pull request by orsonwang**
Port etcd interface to client v3.

### CODE REVIEW

**Comment by RichardKnop** [comment]
@orsonwang Can you update vendor directory in order for tests to pass?

Try this:

```sh
make update-deps
```

**Comment by orsonwang** [comment]
Sorry. I cannot run "make update-deps" as I am using go 1.7, godep cannot work properly with go 1.7. I am using glide instead.

**Comment by orsonwang** [comment]
It seems that test case for config/factory.go did connect to etcd for real, as there's no etcd in the CI environment, it will always fail.

**Comment by RichardKnop** [comment]
@orsonwang It shouldn't fail really. The test was passing before.

**Comment by orsonwang** [comment]
I think so, but I have read recent success CI log. The test never connect to etcd. After my modification, it is trying to connect to etcd, maybe I should write some faking code there.

**Comment by RichardKnop** [comment]
@orsonwang Does the test pass locally? Try running `make test` on your machine.

**Comment by orsonwang** [comment]
Here is my log. But my box is really small and with different psql config, so there are some panics.
`?   	github.com/RichardKnop/go-oauth2-server	[no test files]
?   	github.com/RichardKnop/go-oauth2-server/commands	[no test files]
ok  	github.com/RichardKnop/go-oauth2-server/config	0.016s
ok  	github.com/RichardKnop/go-oauth2-server/database	0.020s
?   	github.com/RichardKnop/go-oauth2-server/health	[no test files]
?   	github.com/RichardKnop/go-oauth2-server/migrations	[no test files]
INFO: 2016/11/23 12:58:13 factory.go:155 ETCD Endpoints: http://localhost:2379
dropdb --if-exists -U go_oauth2_server go_oauth2_server_oauth_test
panic: test timed out after 30s

FAIL	github.com/RichardKnop/go-oauth2-server/oauth	30.028s
?   	github.com/RichardKnop/go-oauth2-server/oauth/mocks	[no test files]
ok  	github.com/RichardKnop/go-oauth2-server/oauth/roles	0.005s
?   	github.com/RichardKnop/go-oauth2-server/oauth/tokentypes	[no test files]
ok  	github.com/RichardKnop/go-oauth2-server/password	0.217s
ok  	github.com/RichardKnop/go-oauth2-server/response	0.006s
ok  	github.com/RichardKnop/go-oauth2-server/routes	0.006s
ok  	github.com/RichardKnop/go-oauth2-server/session	0.016s
INFO: 2016/11/23 13:00:06 bootstrap.go:25 Running bootstrap_migrations migration
(no such table: migrations) 
[2016-11-23 13:00:06]  
INFO: 2016/11/23 13:00:06 bootstrap.go:25 Running bootstrap_migrations migration
(no such table: migrations) 
[2016-11-23 13:00:06]  
dropdb --if-exists -U  
2016/11/23 13:00:06 createdb -U  
2016/11/23 13:00:06 
dropdb --if-exists -U go_oauth2_server go_oauth2_server_database_test
panic: test timed out after 30s
FAIL	github.com/RichardKnop/go-oauth2-server/test-util	30.018s
ok  	github.com/RichardKnop/go-oauth2-server/util	0.007s
?   	github.com/RichardKnop/go-oauth2-server/web	[no test files]
make: *** [test] Error 123`

**Comment by RichardKnop** [comment]
@orsonwang Migrated to v3 API. Do git pull on master please.

**Comment by orsonwang** [comment]
Got it. Thanks.

**Pull request closed without merging**
